project:
  type: website
  output-dir: docs

website:
  title: "Alessandro"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: academico.qmd
        text: Acad√©mico
      - href: finanzas.qmd
        text: Finanzas

format:
  html:
    theme: cosmo
